/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado del servicio y de la base de datos
         * @description Usada por el health check del ALB y por ECS. No requiere token.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista las cuentas del usuario autenticado
         * @description Devuelve solo las cuentas cuyo dueño es el `sub` del token.
         */
        get: operations["listAccounts"];
        put?: never;
        /**
         * Abre una cuenta de débito en MXN para el usuario autenticado
         * @description Asigna una CLABE nueva con dígito verificador válido y publica `account.opened` en el outbox.
         */
        post: operations["openAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        /**
         * Consulta una cuenta y su saldo
         * @description Si la cuenta pertenece a otro usuario responde 404 (protección BOLA).
         */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{accountId}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        /**
         * Movimientos de la cuenta, del más reciente al más antiguo
         * @description Paginación por cursor. El monto se expresa desde la perspectiva del cliente.
         */
        get: operations["listMovements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfiere dinero a otra cuenta Ámbar identificada por CLABE
         * @description Fase 1 solo admite destinos dentro de Ámbar. La transferencia se registra
         *     en un único asiento de doble partida y en la misma transacción se escribe
         *     el evento `transfer.posted` en la tabla outbox.
         *
         *     **Step-up (app móvil).** Si el monto alcanza el umbral o el destino es nuevo
         *     para el usuario, responde 401 con `code: STEP_UP_REQUIRED` y
         *     `WWW-Authenticate: Bearer error="insufficient_user_authentication"` (RFC 9470).
         *     La app pide un reto en `POST /v1/step-up/challenges`, lo firma con la llave
         *     biométrica del dispositivo y repite la transferencia con el header `X-Step-Up`
         *     y la misma `Idempotency-Key`.
         */
        post: operations["createTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dispositivos registrados del usuario
         * @description Solo los del usuario autenticado; nunca expone la llave pública completa.
         */
        get: operations["listDevices"];
        put?: never;
        /**
         * Registra la llave pública de hardware de un dispositivo
         * @description La app genera un par ECDSA P-256 en Android Keystore o Secure Enclave, protegido
         *     con biometría, y envía solo la llave pública (SPKI DER en base64). La llave
         *     privada nunca sale del hardware. Máximo 3 dispositivos activos por usuario.
         */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoca un dispositivo (por ejemplo, si se perdió el teléfono)
         * @description Sus retos pendientes dejan de ser válidos de inmediato.
         */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/step-up/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crea un reto de un solo uso ligado a una operación concreta
         * @description El reto dura 60 segundos y solo sirve para la operación descrita: el
         *     `signing_payload` incluye el hash de la transferencia. Una firma para
         *     $100 a una CLABE no sirve para $10,000 a otra.
         */
        post: operations["createStepUpChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        /**
         * Consulta un asiento con sus postings (operación)
         * @description Vista contable completa del asiento, con signos de débito y crédito. Solo operación.
         */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entryId}/reversals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra un asiento de reverso (el original nunca se modifica)
         * @description Crea un asiento con los postings invertidos. Un asiento solo se reversa una vez y un reverso no se reversa.
         */
        post: operations["reverseEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/qa/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simula un depósito SPEI entrante (solo local, dev y staging)
         * @description Acredita la cuenta contra la cuenta de liquidación SPEI. El servicio no registra esta ruta en producción.
         */
        post: operations["simulateDeposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{deviceId}/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Registra o borra el token de notificaciones push del dispositivo
         * @description Se borra automáticamente al revocar el dispositivo. `null` lo elimina.
         */
        put: operations["setDevicePushToken"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Últimos 50 avisos del usuario
         * @description Incluye el número de avisos sin leer para el indicador de la app.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marca un aviso como leído
         * @description Idempotente; conserva la fecha de la primera lectura.
         */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fraud-cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["FraudCaseId"];
            };
            cookie?: never;
        };
        /**
         * Consulta un caso de posible fraude sobre una transferencia propia
         * @description Solo los casos del usuario autenticado (404 en otro caso).
         */
        get: operations["getFraudCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fraud-cases/{caseId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["FraudCaseId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * El cliente indica si reconoce la transferencia
         * @description Si responde que **no** la reconoce, la cuenta de origen se congela en la misma
         *     transacción (puede recibir dinero, no enviarlo) y se emite `fraud_case.answered`
         *     para que operación dé seguimiento. Repetir la misma respuesta es idempotente;
         *     una respuesta distinta a un caso cerrado devuelve 409.
         */
        post: operations["answerFraudCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/accounts/{accountId}/unfreeze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Descongela una cuenta después de revisar el caso (operación)
         * @description Idempotente. Emite `account.unfrozen` con el operador y el motivo.
         */
        post: operations["unfreezeAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assistant/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Envía una pregunta al asistente y recibe su respuesta
         * @description Sin `conversation_id` empieza una conversación nueva (dura 24 horas). El asistente puede
         *     consultar cuentas, movimientos, un resumen del mes y avisos; no puede hacer operaciones.
         *     Antes de procesar el mensaje se ocultan tarjetas, CLABE, NIP, contraseñas y otros datos
         *     personales, y `notices` le explica al usuario qué se ocultó. El token debe tener también
         *     `accounts.read`: el asistente lo usa tal cual para consultar esta API.
         */
        post: operations["sendAssistantMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assistant/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        /**
         * Historial de una conversación propia (texto ya redactado)
         * @description Solo las conversaciones del usuario autenticado y que no han vencido.
         */
        get: operations["getAssistantConversation"];
        put?: never;
        post?: never;
        /**
         * Borra una conversación propia
         * @description El historial se elimina de inmediato. La auditoría no contiene el texto de la conversación.
         */
        delete: operations["deleteAssistantConversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crea un aviso para un cliente (n8n)
         * @description Idempotente por (`event_id`, destinatario, `kind`): si el flujo se reintenta, devuelve
         *     el aviso original con 200 y no se duplica. La respuesta incluye los tokens push de los
         *     dispositivos activos del cliente para que n8n envíe la notificación.
         */
        post: operations["createNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/fraud-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abre un caso de posible fraude sobre una transferencia (n8n)
         * @description n8n decide *cuándo* (puntaje del evento `transfer.posted`); los datos del caso salen
         *     del asiento, no de la solicitud. Crea en la misma transacción el aviso `FRAUD_CHECK`
         *     con un texto fijo del core. Idempotente por `entry_id`.
         */
        post: operations["openFraudCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conciliación del ledger y salud del outbox (n8n, diaria)
         * @description `ok` es falso si algún saldo no coincide con sus postings, si el ledger no suma cero,
         *     si hay eventos muertos o si el evento pendiente más antiguo tiene más de 5 minutos.
         */
        get: operations["getReconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /**
         * Format: int64
         * @description Monto en centavos de MXN.
         * @example 125050
         */
        Amount: number;
        /**
         * @description CLABE de 18 dígitos (banco, plaza, cuenta y dígito verificador).
         * @example 999180000000000015
         */
        Clabe: string;
        /** @enum {string} */
        Currency: "MXN";
        /** Format: date-time */
        Timestamp: string;
        Account: {
            id: components["schemas"]["Uuid"];
            clabe: components["schemas"]["Clabe"];
            currency: components["schemas"]["Currency"];
            /** @enum {string} */
            status: "ACTIVE" | "FROZEN" | "CLOSED";
            /**
             * Format: int64
             * @description Saldo disponible en centavos.
             */
            balance: number;
            created_at: components["schemas"]["Timestamp"];
        };
        AccountList: {
            data: components["schemas"]["Account"][];
        };
        Movement: {
            /** @description Identificador del posting (entero como texto). */
            id: string;
            entry_id: components["schemas"]["Uuid"];
            kind: components["schemas"]["EntryKind"];
            description: string;
            /**
             * Format: int64
             * @description Centavos desde la perspectiva del cliente; positivo es abono, negativo es cargo.
             */
            amount: number;
            created_at: components["schemas"]["Timestamp"];
        };
        MovementPage: {
            data: components["schemas"]["Movement"][];
            next_cursor: string | null;
        };
        TransferRequest: {
            source_account_id: components["schemas"]["Uuid"];
            destination_clabe: components["schemas"]["Clabe"];
            amount: components["schemas"]["Amount"];
            /** @description Concepto de pago (máximo 40 caracteres, como en SPEI). */
            concept: string;
        };
        Transfer: {
            id: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "POSTED";
            source_account_id: components["schemas"]["Uuid"];
            destination_account_id: components["schemas"]["Uuid"];
            amount: components["schemas"]["Amount"];
            currency: components["schemas"]["Currency"];
            concept: string;
            created_at: components["schemas"]["Timestamp"];
        };
        /** @enum {string} */
        EntryKind: "TRANSFER" | "DEPOSIT" | "REVERSAL";
        Posting: {
            account_id: components["schemas"]["Uuid"];
            /**
             * Format: int64
             * @description Centavos con signo contable (débito positivo, crédito negativo).
             */
            amount: number;
        };
        Entry: {
            id: components["schemas"]["Uuid"];
            kind: components["schemas"]["EntryKind"];
            description: string;
            reverses_id: components["schemas"]["Uuid"] | null;
            created_at: components["schemas"]["Timestamp"];
            postings: components["schemas"]["Posting"][];
        };
        ReversalRequest: {
            reason: string;
        };
        DepositRequest: {
            account_id: components["schemas"]["Uuid"];
            amount: components["schemas"]["Amount"];
            concept: string;
        };
        Device: {
            id: components["schemas"]["Uuid"];
            /** @enum {string} */
            platform: "ios" | "android";
            name: string;
            /** @enum {string} */
            status: "ACTIVE" | "REVOKED";
            created_at: components["schemas"]["Timestamp"];
            last_used_at: components["schemas"]["Timestamp"] | null;
        };
        DeviceList: {
            data: components["schemas"]["Device"][];
        };
        DeviceRegistration: {
            /** @description Llave pública ECDSA P-256 en formato SPKI DER, codificada en base64. */
            public_key: string;
            /** @enum {string} */
            platform: "ios" | "android";
            /** @example iPhone de Ana */
            name: string;
        };
        TransferOperation: {
            /** @enum {string} */
            type: "transfer";
            source_account_id: components["schemas"]["Uuid"];
            destination_clabe: components["schemas"]["Clabe"];
            amount: components["schemas"]["Amount"];
            concept: string;
        };
        StepUpChallengeRequest: {
            device_id: components["schemas"]["Uuid"];
            operation: components["schemas"]["TransferOperation"];
        };
        StepUpChallenge: {
            id: components["schemas"]["Uuid"];
            expires_at: components["schemas"]["Timestamp"];
            /** @description Texto exacto que el dispositivo firma (UTF-8) con SHA256withECDSA. */
            signing_payload: string;
        };
        PushTokenRequest: {
            push_token: string | null;
        };
        /** @enum {string} */
        NotificationKind: "WELCOME" | "TRANSFER_SENT" | "TRANSFER_RECEIVED" | "DEPOSIT_RECEIVED" | "FRAUD_CHECK" | "ACCOUNT_FROZEN" | "SECURITY";
        /** @description Referencias para navegar desde el aviso. Nunca datos personales. */
        NotificationData: {
            account_id?: components["schemas"]["Uuid"];
            entry_id?: components["schemas"]["Uuid"];
            fraud_case_id?: components["schemas"]["Uuid"];
        };
        Notification: {
            id: components["schemas"]["Uuid"];
            kind: components["schemas"]["NotificationKind"];
            title: string;
            body: string;
            data: components["schemas"]["NotificationData"];
            created_at: components["schemas"]["Timestamp"];
            read_at: components["schemas"]["Timestamp"] | null;
        };
        NotificationInbox: {
            data: components["schemas"]["Notification"][];
            unread_count: number;
        };
        /** @enum {string} */
        RiskReason: "NEW_BENEFICIARY" | "UNUSUAL_AMOUNT" | "NIGHT_TIME" | "HIGH_VELOCITY";
        /** @description Campos comunes de un caso (sin restringir propiedades extra; ver FraudCase). */
        FraudCaseFields: {
            id: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "OPEN" | "RECOGNIZED" | "NOT_RECOGNIZED";
            reasons: components["schemas"]["RiskReason"][];
            created_at: components["schemas"]["Timestamp"];
            resolved_at: components["schemas"]["Timestamp"] | null;
            transfer: {
                entry_id: components["schemas"]["Uuid"];
                amount: components["schemas"]["Amount"];
                concept: string;
                destination_clabe_last4: string;
                created_at: components["schemas"]["Timestamp"];
            };
        };
        /** @description El cliente ve los motivos, no el puntaje. */
        FraudCase: components["schemas"]["FraudCaseFields"];
        FraudCaseAnswer: {
            recognized: boolean;
        };
        FraudCaseResolution: components["schemas"]["FraudCaseFields"] & {
            account_frozen: boolean;
        };
        UnfreezeRequest: {
            reason: string;
        };
        /** @description Destinatario por `owner_id` o por `account_id` (exactamente uno). */
        InternalNotificationRequest: {
            event_id: components["schemas"]["Uuid"];
            kind: components["schemas"]["NotificationKind"];
            owner_id?: string;
            account_id?: components["schemas"]["Uuid"];
            title: string;
            body: string;
            data?: components["schemas"]["NotificationData"];
        } & (unknown | unknown);
        InternalNotificationResult: {
            notification: components["schemas"]["Notification"];
            created: boolean;
            push_tokens: string[];
        };
        InternalFraudCaseRequest: {
            entry_id: components["schemas"]["Uuid"];
        };
        InternalFraudCaseResult: {
            fraud_case: components["schemas"]["FraudCaseFields"] & {
                score: number;
                account_id: components["schemas"]["Uuid"];
            };
            created: boolean;
            notification: components["schemas"]["Notification"];
            push_tokens: string[];
        };
        ReconciliationReport: {
            checked_at: components["schemas"]["Timestamp"];
            ok: boolean;
            ledger: {
                checked_at: components["schemas"]["Timestamp"];
                accounts_checked: number;
                drift: {
                    id: components["schemas"]["Uuid"];
                    code: string | null;
                    clabe: string | null;
                    /** Format: int64 */
                    stored_balance: number;
                    /** Format: int64 */
                    derived_balance: number;
                }[];
                /** Format: int64 */
                ledger_total: number;
                ok: boolean;
            };
            outbox: {
                pending: number;
                dead: number;
                oldest_pending_seconds: number;
            };
        };
        AssistantMessageRequest: {
            conversation_id?: components["schemas"]["Uuid"];
            /** @example ¿En qué gasté más este mes? */
            message: string;
        };
        AssistantReply: {
            conversation_id: components["schemas"]["Uuid"];
            reply: {
                text: string;
                created_at: components["schemas"]["Timestamp"];
            };
            /** @description Consultas que hizo el asistente para responder (transparencia para el usuario). */
            tools_used: ("consultar_cuentas" | "consultar_movimientos" | "resumen_del_mes" | "consultar_avisos")[];
            /** @description Avisos de privacidad, p. ej. que se ocultó una tarjeta del mensaje. */
            notices: string[];
        };
        AssistantConversation: {
            id: components["schemas"]["Uuid"];
            messages: {
                /** @enum {string} */
                role: "user" | "assistant";
                text: string;
                created_at: components["schemas"]["Timestamp"];
            }[];
            created_at: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
        };
        /** @description RFC 9457 Problem Details. */
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /**
             * @description Código estable para clientes y QA. Valores actuales:
             *     VALIDATION_ERROR, UNAUTHENTICATED, FORBIDDEN, NOT_FOUND,
             *     INSUFFICIENT_FUNDS, ACCOUNT_NOT_ACTIVE, SAME_ACCOUNT,
             *     IDEMPOTENCY_KEY_REUSED, ALREADY_REVERSED, NOT_REVERSIBLE,
             *     STEP_UP_REQUIRED, DEVICE_LIMIT_REACHED, FRAUD_CASE_CLOSED,
             *     RATE_LIMITED, CONVERSATION_FULL, CONVERSATION_BUSY, ASSISTANT_UNAVAILABLE.
             */
            code: string;
            errors?: {
                path: string;
                message: string;
            }[];
            /** @description Solo con code STEP_UP_REQUIRED. */
            step_up?: {
                /** @enum {string} */
                reason: "AMOUNT_THRESHOLD" | "NEW_BENEFICIARY" | "INVALID_PROOF";
                /** Format: int64 */
                threshold?: number;
            };
        };
    };
    responses: {
        /** @description La solicitud no cumple el contrato */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Falta el token o es inválido */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Falta el token, es inválido, o la operación requiere confirmación biométrica (STEP_UP_REQUIRED) */
        UnauthenticatedOrStepUp: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El token no tiene el scope requerido */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El recurso no existe o no pertenece al usuario */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description La Idempotency-Key ya se usó con un cuerpo distinto */
        IdempotencyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El recurso está en un estado que no admite esta operación */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Se alcanzó un límite de uso */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Una dependencia (p. ej. el modelo de IA) no está disponible */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description La operación viola una regla de negocio (fondos, estado de la cuenta) */
        BusinessRule: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        AccountId: string;
        EntryId: string;
        DeviceId: string;
        ConversationId: string;
        NotificationId: string;
        FraudCaseId: string;
        /** @description `<challenge_id>.<firma>`: la firma ECDSA (DER, base64url) del `signing_payload` del reto. */
        StepUpProof: string;
        /** @description UUID generado por el cliente; se reutiliza en cada reintento de la misma operación. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicio sano */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** @enum {string} */
                        database: "ok";
                    };
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuentas del usuario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    openAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuenta abierta con CLABE asignada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuenta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listMovements: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Valor `next_cursor` de la página anterior. */
                cursor?: string;
            };
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de movimientos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementPage"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createTransfer: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generado por el cliente; se reutiliza en cada reintento de la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description `<challenge_id>.<firma>`: la firma ECDSA (DER, base64url) del `signing_payload` del reto. */
                "X-Step-Up"?: components["parameters"]["StepUpProof"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description Transferencia registrada (o repetición idempotente) */
            201: {
                headers: {
                    /** @description `true` cuando la respuesta es la original de una solicitud repetida. */
                    "Idempotent-Replayed"?: "true" | "false";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthenticatedOrStepUp"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["BusinessRule"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dispositivos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegistration"];
            };
        };
        responses: {
            /** @description Dispositivo registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["BusinessRule"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dispositivo revocado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createStepUpChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepUpChallengeRequest"];
            };
        };
        responses: {
            /** @description Reto creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepUpChallenge"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asiento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reverseEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generado por el cliente; se reutiliza en cada reintento de la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReversalRequest"];
            };
        };
        responses: {
            /** @description Asiento de reverso registrado */
            201: {
                headers: {
                    "Idempotent-Replayed"?: "true" | "false";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["BusinessRule"];
        };
    };
    simulateDeposit: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generado por el cliente; se reutiliza en cada reintento de la misma operación. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositRequest"];
            };
        };
        responses: {
            /** @description Depósito registrado */
            201: {
                headers: {
                    "Idempotent-Replayed"?: "true" | "false";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["BusinessRule"];
        };
    };
    setDevicePushToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenRequest"];
            };
        };
        responses: {
            /** @description Token actualizado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avisos, del más reciente al más antiguo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationInbox"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aviso marcado como leído */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getFraudCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["FraudCaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FraudCase"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    answerFraudCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["FraudCaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FraudCaseAnswer"];
            };
        };
        responses: {
            /** @description Caso resuelto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FraudCaseResolution"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    unfreezeAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnfreezeRequest"];
            };
        };
        responses: {
            /** @description Cuenta activa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sendAssistantMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantMessageRequest"];
            };
        };
        responses: {
            /** @description Respuesta del asistente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantReply"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    getAssistantConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantConversation"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAssistantConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversación borrada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalNotificationRequest"];
            };
        };
        responses: {
            /** @description El aviso ya existía */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalNotificationResult"];
                };
            };
            /** @description Aviso creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalNotificationResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    openFraudCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalFraudCaseRequest"];
            };
        };
        responses: {
            /** @description El caso ya existía */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalFraudCaseResult"];
                };
            };
            /** @description Caso abierto */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalFraudCaseResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reporte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationReport"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
}
